# dingo : a python library for metabolic networks sampling and analysis
# dingo is part of GeomScale project

# Copyright (c) 2021-2022 Vissarion Fisikopoulos

# Licensed under GNU LGPL.3, see LICENCE file

name: dingo-ubuntu

on: [push, pull_request]

jobs:
  build-linux:
    name: Build Linux-based distributions

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Load submodules
        run: |
          git submodule update --init;

      - name: Download and unzip the boost library
        run: |
          curl -O https://archives.boost.io/release/1.76.0/source/boost_1_76_0.tar.bz2;
          tar -xjf boost_1_76_0.tar.bz2;
          rm boost_1_76_0.tar.bz2;

      - name: Download and unzip the lp-solve library
        run: |
          wget https://sourceforge.net/projects/lpsolve/files/lpsolve/5.5.2.11/lp_solve_5.5.2.11_source.tar.gz
          tar xzvf lp_solve_5.5.2.11_source.tar.gz
          rm lp_solve_5.5.2.11_source.tar.gz

      - name: Install dependencies
        run: |
          sudo apt-get install libsuitesparse-dev;
          pip install --upgrade setuptools wheel cython numpy
          pip install cibuildwheel

      - name: Build wheels for Linux
        # run: CIBW_SKIP="pp*" CIBW_BUILD="cp310*" CIBW_PYTHON_VERSION="3.10" cibuildwheel --output-dir dist
        env:
          CIBW_BUILD: "cp310-manylinux_x86_64" # Remove -manylinux_x86_64 once everything works fine to build all distributions
          CIBW_SKIP: "pp*"
          CIBW_ARCHS_LINUX: "x86_64"
          CIBW_PYTHON_VERSION: "3.10"
        run: |
          cibuildwheel --output-dir dist

      - uses: actions/upload-artifact@v4
        with:
          name: wheels
          path: dist/

      - name: Install built wheel on the gh VM to run tests (only cp310)
        run: |
          echo "All wheels in dist/"
          ls dist/
          WHEEL_FILE=$(ls dist/*cp310*manylinux*_x86_64.whl | head -n 1)
          pip install "$WHEEL_FILE"

      - name: Run tests
        run: |
          python3 tests/fba.py;
          python3 tests/full_dimensional.py;
          python3 tests/max_ball.py;
          python3 tests/scaling.py;
          python3 tests/sampling.py;
          python3 tests/sampling_no_multiphase.py;

  # ------------------------------------------------------------------------------------------

  # ------------------------------------------------------------------------------------------

  publish-testpypi:
    name: Upload to TestPyPI
    needs: [build-linux] # build-macos
    runs-on: ubuntu-latest
    environment:
      name: testpypi

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: wheels
          path: dist/

      - name: Install Twine
        run: python -m pip install twine

      # - name: Publish to TestPyPI
      #   run: |
      #     twine upload --repository testpypi dist/*
      #   env:
      #     TWINE_USERNAME: __token__
      #     TWINE_PASSWORD: ${{ secrets.TESTPYPI_API_TOKEN }}

      - name: Publish package to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository-url: https://test.pypi.org/legacy/
          packages-dir: dist/
