# dingo : a python library for metabolic networks sampling and analysis
# dingo is part of GeomScale project

# Copyright (c) 2021-2022 Vissarion Fisikopoulos

# Licensed under GNU LGPL.3, see LICENCE file

name: dingo-ubuntu

on: [push, pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Load submodules
        run: |
          git submodule update --init;

      - name: Download and unzip the boost library
        run: |
          curl -O https://archives.boost.io/release/1.76.0/source/boost_1_76_0.tar.bz2;
          tar -xjf boost_1_76_0.tar.bz2;
          rm boost_1_76_0.tar.bz2;

      - name: Download and unzip the lp-solve library
        run: |
          wget https://sourceforge.net/projects/lpsolve/files/lpsolve/5.5.2.11/lp_solve_5.5.2.11_source.tar.gz
          tar xzvf lp_solve_5.5.2.11_source.tar.gz
          rm lp_solve_5.5.2.11_source.tar.gz

      - name: Install dependencies
        run: |
          sudo apt-get install libsuitesparse-dev;
          pip install --upgrade setuptools wheel cython numpy
          pip install cibuildwheel

      - name: Build wheels for Linux
        run: cibuildwheel --output-dir dist
        env:
          CIBW_PLATFORM: linux
          CIBW_PYTHON_VERSION: 3.8 # Target Python 3.8 for wheel build

      - uses: actions/upload-artifact@v4
        with:
          name: wheels
          path: dist/

      - name: Install the built wheel
        run: pip install dist/*.whl # Install from the built wheel file

      - name: Run tests
        run: |
          python3 tests/fba.py;
          python3 tests/full_dimensional.py;
          python3 tests/max_ball.py;
          python3 tests/scaling.py;
          python3 tests/sampling.py;
          python3 tests/sampling_no_multiphase.py;

  # build-macos:

  publish-testpypi:
    name: Upload to TestPyPI
    needs: [build-linux] # build-macos
    runs-on: ubuntu-latest
    environment:
      name: testpypi

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: wheels
          path: dist/

      - name: Install Twine
        run: python -m pip install twine

      - name: Publish to TestPyPI
        run: |
          twine upload --repository-url https://test.pypi.org/legacy/ dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TESTPYPI_API_TOKEN }}
