# dingo : a python library for metabolic networks sampling and analysis
# dingo is part of GeomScale project

# Copyright (c) 2021-2022 Vissarion Fisikopoulos

# Licensed under GNU LGPL.3, see LICENCE file

name: dingo-ubuntu

on: [push, pull_request]

jobs:
  # Linux
  build-linux:
    name: Build Linux-based distributions

    runs-on: ubuntu-latest
    permissions:
      id-token: write

    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Load submodules
        run: |
          git submodule update --init;

      - name: Download and unzip the boost library
        run: |
          curl -O https://archives.boost.io/release/1.76.0/source/boost_1_76_0.tar.bz2;
          tar -xjf boost_1_76_0.tar.bz2;
          rm boost_1_76_0.tar.bz2;

      - name: Download and unzip the lp-solve library
        run: |
          wget https://sourceforge.net/projects/lpsolve/files/lpsolve/5.5.2.11/lp_solve_5.5.2.11_source.tar.gz
          tar xzvf lp_solve_5.5.2.11_source.tar.gz
          rm lp_solve_5.5.2.11_source.tar.gz

      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install libsuitesparse-dev;
          pip install --upgrade setuptools wheel cython numpy
          pip install cibuildwheel

      - name: Clean previous builds
        run: rm -rf build dist *.egg-info

      - name: Build wheels for Linux
        env:
          CIBW_BUILD: "cp310-manylinux_x86_64" # Remove -manylinux_x86_64 once everything works fine to build all distributions
          CIBW_SKIP: "pp*"
          CIBW_ARCHS_LINUX: "x86_64"
          CIBW_PYTHON_VERSION: "3.10"
        run: |
          cibuildwheel --output-dir dist

      - uses: actions/upload-artifact@v4
        with:
          name: linux-wheels
          path: dist/

      # - name: Install built wheel on the gh VM to run tests (only cp310)
      #   run: |
      #     echo "All wheels in Linux dist/"
      #     ls dist/
      #     WHEEL_FILE=$(ls dist/*cp310*manylinux*_x86_64.whl | head -n 1)
      #     pip install "$WHEEL_FILE"

      # - name: Run tests
      #   run: |
      #     python3 tests/fba.py;
      #     python3 tests/full_dimensional.py;
      #     python3 tests/max_ball.py;
      #     python3 tests/scaling.py;
      #     python3 tests/sampling.py;
      #     python3 tests/sampling_no_multiphase.py;

  # ------------------------------------------------------------------------------------------

  # MacOS
  build-macos:
    name: Build macOS distributions
    runs-on: macos-13
    permissions:
      id-token: write

    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Load submodules
        run: |
          git submodule update --init

      - name: Modify Template Usage
        run: |
          # Modify the template function calls in the specified files using sed
          sed -i '' 's/walk\.template parameters_burnin(/walk.template parameters_burnin<>(/' volesti/include/sampling/mmcs.hpp
          sed -i '' 's/walk\.template get_starting_point(/walk.template get_starting_point<>(/' volesti/include/sampling/mmcs.hpp
          sed -i '' 's/walk\.template parameters_burnin(/walk.template parameters_burnin<>(/' volesti/include/sampling/parallel_mmcs.hpp
          sed -i '' 's/walk\.template get_starting_point(/walk.template get_starting_point<>(/' volesti/include/sampling/parallel_mmcs.hpp

      - name: Download Boost
        run: |
          curl -O https://archives.boost.io/release/1.76.0/source/boost_1_76_0.tar.bz2
          tar -xjf boost_1_76_0.tar.bz2
          rm boost_1_76_0.tar.bz2

      - name: Download lp_solve
        run: |
          curl -L -o lp_solve_5.5.2.11_source.tar.gz https://sourceforge.net/projects/lpsolve/files/lpsolve/5.5.2.11/lp_solve_5.5.2.11_source.tar.gz/download
          tar xzvf lp_solve_5.5.2.11_source.tar.gz
          rm lp_solve_5.5.2.11_source.tar.gz

      - name: Install Homebrew deps
        run: |
          brew install --formula suite-sparse llvm libomp
          echo "HOMEBREW_PREFIX=$(brew --prefix)" >> $GITHUB_ENV

      - name: Check compiler
        run: |
          which clang++
          clang++ --version

      - name: List files in suite-sparse
        run: |
          HOMEBREW_PREFIX=$(brew --prefix)
          find $HOMEBREW_PREFIX/opt/suite-sparse/include/suitesparse -type f
          echo "-----"
          find $HOMEBREW_PREFIX/opt/suite-sparse/lib -type f

      - name: Install Python build tools
        run: |
          pip install --upgrade pip setuptools wheel cython numpy cibuildwheel

      - name: Clean previous builds
        run: rm -rf build dist *.egg-info

      - name: Build wheels for macOS
        env:
          # CIBW_BUILD: "cp310-macosx_arm64" # cp310-macosx_x86_64
          # CIBW_ARCHS_MACOS: "arm64" # x86_64
          # CIBW_BUILD: "cp310-macosx_x86_64"
          # CIBW_ARCHS_MACOS: "x86_64" #
          CIBW_BUILD: "cp310-macosx_universal2"
          CIBW_ARCHS_MACOS: "universal2"

          MACOSX_DEPLOYMENT_TARGET: "13.0"

        run: |
          HOMEBREW_PREFIX=$(brew --prefix)
          echo "PATH=$HOMEBREW_PREFIX/opt/llvm/bin:$PATH" >> $GITHUB_ENV

          export CC=$HOMEBREW_PREFIX/opt/llvm/bin/clang
          export CXX=$HOMEBREW_PREFIX/opt/llvm/bin/clang++

          CIBW_ENVIRONMENT="\
            CC=$CC \
            CXX=$CXX \
            CFLAGS='-O3 -arch x86_64 -I$HOMEBREW_PREFIX/opt/suite-sparse/include/suitesparse' \
            CXXFLAGS='-O3 -std=c++17 -arch x86_64 -stdlib=libc++ -Wno-deprecated-declarations' \
            LDFLAGS='-stdlib=libc++ -L$HOMEBREW_PREFIX/opt/llvm/lib -L$HOMEBREW_PREFIX/opt/suite-sparse/lib -lomp'"

          export CIBW_ENVIRONMENT

          cibuildwheel --platform macos --output-dir dist

      - uses: actions/upload-artifact@v4
        with:
          name: macos-wheels
          path: dist/

          # for whl in dist/*.whl; do
          #   unzip "$whl" -d wheel_unpack
          #   METADATA=$(find wheel_unpack -name METADATA)
          #   sed -i '' '/^Dynamic: license-file/d' "$METADATA"
          #   rm "$whl"
          #   (cd wheel_unpack && zip -r "../$(basename $whl)" .)
          #   rm -rf wheel_unpack
          # done

      # - name: Install dependencies and set flags for SuiteSparse
      #   run: |
      #     export CFLAGS="-I/usr/local/opt/suite-sparse/include/suitesparse"
      #     export LDFLAGS="-L/usr/local/opt/suite-sparse/lib"

      #     pip install sparseqr

      # - name: Install and test the built wheel
      #   run: |
      #     echo "All wheels in macos dist/"
      #     ls dist/
      #     WHEEL_FILE=$(ls dist/*cp310*macosx*.whl | head -n 1)
      #     echo "Installing $WHEEL_FILE"
      #     pip install "$WHEEL_FILE"

      # - name: Run tests
      #   run: |
      #     # Ensures that only the Homebrew-provided libomp.dylib is loaded, avoiding that conflict.
      #     export DYLD_LIBRARY_PATH="$HOMEBREW_PREFIX/opt/libomp/lib:$DYLD_LIBRARY_PATH"

      #     python3 tests/fba.py
      #     python3 tests/full_dimensional.py
      #     python3 tests/max_ball.py
      #     python3 tests/scaling.py
      #     python3 tests/sampling.py

      #     # For some reason, only sometimes, not always, the test fails on macOS, with the following error:
      #     # Assertion failed: (min_arg <= max_arg), function uniform_int_distribution, file uniform_int_distribution.hpp, line 337.

      #     # python3 tests/sampling_no_multiphase.py

  # ------------------------------------------------------------------------------------------

  # Publish
  publish-testpypi:
    name: Upload to TestPyPI
    needs: [build-linux, build-macos]
    runs-on: ubuntu-latest
    environment:
      name: testpypi

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: linux-wheels
          path: dist/

      - uses: actions/download-artifact@v4
        with:
          name: macos-wheels
          path: dist/

      - name: Install Twine
        run: python -m pip install twine

      - name: List built wheels
        run: |
          echo "All wheels built during the distribution-specific jobs (in dist/)"
          ls dist/

      - name: Fix wheels metadata
        run: |
          mkdir -p fixed_dist
          for whl in dist/*.whl; do
            mkdir -p wheel_unpack
            unzip "$whl" -d wheel_unpack

            METADATA=$(find wheel_unpack -name METADATA)
            sed -i '/^Dynamic: license-file/d' "$METADATA"

            fixed_whl="fixed_dist/$(basename "$whl")"
            (cd wheel_unpack && zip -r "../${fixed_whl}" .)

            rm -rf wheel_unpack
          done

          # Replace old wheels with fixed ones
          rm dist/*.whl
          mv fixed_dist/*.whl dist/

      - name: List built wheels after fixing metadata
        run: |
          echo "All wheels built during the distribution-specific jobs (in dist/)"
          ls dist/

      - name: Publish to TestPyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TESTPYPI_API_TOKEN }}
        run: |
          twine check dist/*
          twine upload --repository-url https://test.pypi.org/legacy/ dist/*
